cain: configs have collected | msg:

diff --git a/cain b/cain
--- a/cain
+++ b/cain
@@ -16,15 +16,24 @@
 #                Copyright (c) 2025 Rhett Applestone                 #
 # ================================================================== #
 
+# ==================== Error handling function ===================== #
 
-
+handle_error () {
+	echo "An error has occured" && exit 1 
+}
 
 # ==================== Making the cli look nice ==================== #
-cat ~/cain/files/casi ||( echo "error" && exit 1)
+cat ~/cain/files/cai || handle_error
 # ====================== Collecting Files ========================== #
 
 # Collecting .bashrc and error handling
 cp ~/.bashrc ~/cain/files/dotfiles
+if [ $? -eq 0 ]; then
+	echo ".bashrc collected successfully"
+else
+	echo "Error has occured collecting .bashrc" && exit 1
+
+fi
 
 # Collecting configs for cinnamon desktop enviornment and error handling
 dconf dump / > ~/cain/files/cinnamon/cinnamon-settings
diff --git a/install b/install
--- a/install
+++ b/install
@@ -21,6 +21,9 @@
 
 # Making Making everything look pretty
 cat ~/cain/files/cai
+if [ $? -ne 0 ]; then
+	echo "Error has occured printing cain ascii art in ~/cain/files/cai" && exit 1
+fi
 
 # Update to most reecent apt repos
 sudo apt update -y
